### PR TITLE
feat(react): Add rules on React props

### PR DESCRIPTION
**Pull request by pixelastic**
This will:

- check for duplicates in React components props
- make sure props are sorted alphabetically
- make sure propType are sorted alphabetically

### CODE REVIEW

**Comment by vvo** [comment]
Wee, can you do a minor release afterwards?

**Comment by pixelastic** [comment]
Sure. Is that just `npm version minor && npm publish` ?

**Comment by vvo** [comment]
never used npm version minor but yes we just need to bump package.json and npm publish (tagging on git is not mandatory but always a +).

**Comment by vvo** [comment]
And we then need to upgrade instantsearch.js dep

**Comment by pixelastic** [comment]
Ok, I'll handle that.

**Pull request merged**
