### PR TITLE
fix: upgrade packages

### PR DESCRIPTION
**Pull request by millotp**
Because `babel-eslint` is now deprecated, and some dependencies were missing in the test, and`yarn test` was not working anymore, this PR upgrade all dependencies and fix `yarn test`.

### CODE REVIEW

**Review by bodinsamuel — APPROVED** [review]
thanks 👌🏻

**Comment by Haroenv** [comment]
the readme needs to be updated too :)

**Comment by millotp** [comment]
> the readme needs to be updated too :)

I changed `babel-parser` to `@babel/eslint-parser`, do I also need to add `@babel/core` ?

**Review by Haroenv — APPROVED** [review]
sorry, missed the readme edit

As this probably should be released as a major, don't forget to put in the commit message something like:

BREAKING CHANGE: different peer dependency "@babel/eslint-parser" is now used

**Pull request merged**
