### PR TITLE
rule(react): disallow binding in render

### PR DESCRIPTION
**Pull request by Haroenv**
reading: https://medium.com/@housecor/react-pattern-extract-child-components-to-avoid-binding-e3ad8310725e

### CODE REVIEW

**Comment by vvo** [comment]
Should we allow for refs? https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#ignorerefs

**Comment by Haroenv** [comment]
I'm not sure. We use it in React instantsearch right

**Comment by vvo** [comment]
Yes we use it, was just wondering if you had dig this and how painful it would be. Let's go with this rule (release should be minor).

**Comment by samouss** [comment]
Sure about this change? Maybe we can keep the arrow function? 
A lots of discussion around render props recently, they can be really convenient.

> https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578

> https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce

**Comment by Haroenv** [comment]
Arrow fns should be good I think

**Comment by vvo** [comment]
Just used them yep, in many cases arrow function are just OK, only in hot loops and there you'll have to be careful that's it.

**Pull request merged**
