### PR TITLE
chore(release): allow beta

### PR DESCRIPTION
**Pull request by Haroenv**
This is slightly different than in react-instantsearch, because a new prompt is easier to remember than a tag to add

### CODE REVIEW

**Comment by Haroenv** [comment]
I'm really doubting if we shouldn't use an existing "release" package, or make our own, even if it's a shell script. This comes up a lot 😄

**Comment by vvo** [comment]
Sorry I don't think it's necessary to have a way to do beta releases. Basically you can just do npm publish --tag beta at any moment locally and that works (without even comitting or anything).

Here we enforce every release to provide the tag (it asks for it). While 99% of the time we don't do beta releases.

And in this particular project, when we do beta releases, it's actually not comitted nor pushed to master (so we won't do beta releases the way you propose, just npm publish locally).

For this kind of project, there's no need to have an official beta release track. (again sorry that was not clear)

**Comment by Haroenv** [comment]
Sure, that makes sense, that was actually what I did when trying the beta yesterday as well. I'm just wondering if it's sustainable to have a specific release file in each of our repositories, WDYT about adding an npm package which has this file — or a proper one from react-instantsearch — as a `bin` entry? That way it's sharable, but it's still simple and bash

**Comment by vvo** [comment]
> Sure, that makes sense, that was actually what I did when trying the beta yesterday as well. I'm just wondering if it's sustainable to have a specific release file in each of our repositories, WDYT about adding an npm package which has this file — or a proper one from react-instantsearch — as a bin entry? That way it's sharable, but it's still simple and bash

Yes I never did it but having a programmatic module to achieve our release cycle would be ideal. Never took the time to do it because copy pasting the script and customizing it for the project was always faster and the release tooling was not a priority.

Hard to know if it's valuable or not to have a common module.

**Pull request closed without merging**
